# Generated by Django 5.0 on 2023-12-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerform',
            name='domain',
            field=models.CharField(default='select', max_length=10),
        ),
    ]
