# Generated by Django 5.0 on 2023-12-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_uploadfiles_alter_registerform_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='uploaded_at',
        ),
    ]
