# Generated by Django 5.0 on 2023-12-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
