# Generated by Django 5.0 on 2023-12-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_uploadfiles_authorname_uploadfiles_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='username',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
